% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{lmodern}
\usepackage{ifxetex,ifluatex}
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\hypersetup{
  pdftitle={R Notebook},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}
\urlstyle{same} % disable monospaced font for URLs
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifluatex
  \usepackage{selnolig}  % disable illegal ligatures
\fi

\title{R Notebook}
\author{}
\date{\vspace{-2.5em}}

\begin{document}
\maketitle

This is an \href{http://rmarkdown.rstudio.com}{R Markdown} Notebook.
When you execute code within the notebook, the results appear beneath
the code.

Try executing this chunk by clicking the \emph{Run} button within the
chunk or by placing your cursor inside it and pressing
\emph{Ctrl+Shift+Enter}.

Add a new chunk by clicking the \emph{Insert Chunk} button on the
toolbar or by pressing \emph{Ctrl+Alt+I}.

When you save the notebook, an HTML file containing the code and output
will be saved alongside it (click the \emph{Preview} button or press
\emph{Ctrl+Shift+K} to preview the HTML file).

The preview shows you a rendered HTML copy of the contents of the
editor. Consequently, unlike \emph{Knit}, \emph{Preview} does not run
any R code chunks. Instead, the output of the chunk when it was last run
in the editor is displayed.

\hypertarget{dependency}{%
\subsubsection{Dependency}\label{dependency}}

\begin{Shaded}
\begin{Highlighting}[]
\DocumentationTok{\#\#library(tidyverse)}
\FunctionTok{library}\NormalTok{(dplyr)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Attaching package: 'dplyr'
\end{verbatim}

\begin{verbatim}
## The following objects are masked from 'package:stats':
## 
##     filter, lag
\end{verbatim}

\begin{verbatim}
## The following objects are masked from 'package:base':
## 
##     intersect, setdiff, setequal, union
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(readxl)}
\FunctionTok{library}\NormalTok{(ggplot2)}
\FunctionTok{library}\NormalTok{(ggpubr)}
\end{Highlighting}
\end{Shaded}

\hypertarget{read-xls-file}{%
\subsubsection{Read xls file}\label{read-xls-file}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{file\_name }\OtherTok{=} \StringTok{"Hydrocarbon(2).xlsx"}
\NormalTok{df }\OtherTok{=} \FunctionTok{read\_excel}\NormalTok{(file\_name)}
\end{Highlighting}
\end{Shaded}

\hypertarget{preview-tibble}{%
\subsubsection{Preview tibble}\label{preview-tibble}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{df}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 32 x 6
##    Index    X1    X2    X3    X4     Y
##    <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>
##  1     1    33    53  3.32  3.42    29
##  2     2    31    36  3.1   3.26    24
##  3     3    33    51  3.18  3.18    26
##  4     4    37    51  3.39  3.08    22
##  5     5    36    54  3.2   3.41    27
##  6     6    35    35  3.03  3.03    21
##  7     7    59    56  4.78  4.57    33
##  8     8    60    60  4.72  4.72    34
##  9     9    59    60  4.6   4.41    32
## 10    10    60    60  4.53  4.53    34
## # ... with 22 more rows
\end{verbatim}

\hypertarget{q-1}{%
\section{Q-1}\label{q-1}}

\hypertarget{summary}{%
\subsection{SUmmary}\label{summary}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(df)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##      Index             X1              X2              X3       
##  Min.   : 1.00   Min.   :31.00   Min.   :35.00   Min.   :2.590  
##  1st Qu.: 8.75   1st Qu.:37.00   1st Qu.:41.00   1st Qu.:3.290  
##  Median :16.50   Median :60.00   Median :60.00   Median :4.285  
##  Mean   :16.50   Mean   :57.91   Mean   :55.91   Mean   :4.422  
##  3rd Qu.:24.25   3rd Qu.:62.00   3rd Qu.:62.00   3rd Qu.:4.630  
##  Max.   :32.00   Max.   :92.00   Max.   :92.00   Max.   :7.450  
##        X4              Y        
##  Min.   :2.590   Min.   :16.00  
##  1st Qu.:3.373   1st Qu.:23.75  
##  Median :4.090   Median :31.50  
##  Mean   :4.324   Mean   :31.12  
##  3rd Qu.:4.540   3rd Qu.:34.50  
##  Max.   :7.450   Max.   :55.00
\end{verbatim}

\hypertarget{histogram}{%
\subsection{Histogram}\label{histogram}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggplot}\NormalTok{(df, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x=}\NormalTok{Y)) }\SpecialCharTok{+} \FunctionTok{geom\_histogram}\NormalTok{(}\AttributeTok{bins=}\DecValTok{20}\NormalTok{) }\SpecialCharTok{+} \FunctionTok{labs}\NormalTok{( }\AttributeTok{y=}\StringTok{"Counts"}\NormalTok{, }\AttributeTok{x=}\StringTok{"Hydrocarbon escaping"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{midterm_pt2_mir_files/figure-latex/unnamed-chunk-5-1.pdf}

\hypertarget{histogram-with-density-curve}{%
\subsection{Histogram with density
curve}\label{histogram-with-density-curve}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggplot}\NormalTok{(df, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x=}\NormalTok{Y)) }\SpecialCharTok{+} \FunctionTok{geom\_histogram}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{y=}\NormalTok{..density..),}\AttributeTok{bins=}\DecValTok{20}\NormalTok{) }\SpecialCharTok{+} \FunctionTok{geom\_density}\NormalTok{(}\AttributeTok{alpha=}\NormalTok{.}\DecValTok{2}\NormalTok{)}\SpecialCharTok{+} \FunctionTok{labs}\NormalTok{( }\AttributeTok{y=}\StringTok{"Density"}\NormalTok{, }\AttributeTok{x=}\StringTok{"Hydrocarbon escaping"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{midterm_pt2_mir_files/figure-latex/unnamed-chunk-6-1.pdf}

\emph{So looking at the graphs above, we can see that the curve is right
skewed. This means more observations were found with hydrocarbon
escaping values less than mean}

\hypertarget{q-2}{%
\section{Q-2}\label{q-2}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{fit}\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(df}\SpecialCharTok{$}\NormalTok{Y}\SpecialCharTok{\textasciitilde{}}\NormalTok{df}\SpecialCharTok{$}\NormalTok{X4)}
\FunctionTok{summary}\NormalTok{(fit)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = df$Y ~ df$X4)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -9.2820 -2.1353  0.3438  2.0466  7.2629 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(>|t|)    
## (Intercept)   4.3054     2.1674   1.986   0.0562 .  
## df$X4         6.2029     0.4779  12.980 7.65e-14 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 3.703 on 30 degrees of freedom
## Multiple R-squared:  0.8489, Adjusted R-squared:  0.8438 
## F-statistic: 168.5 on 1 and 30 DF,  p-value: 7.654e-14
\end{verbatim}

\hypertarget{scatter-plot}{%
\subsection{Scatter plot}\label{scatter-plot}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#create plot with regression line, regression equation, and R{-}squared}
\FunctionTok{ggplot}\NormalTok{(}\AttributeTok{data=}\NormalTok{df, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x=}\NormalTok{X4, }\AttributeTok{y=}\NormalTok{Y)) }\SpecialCharTok{+}
        \FunctionTok{geom\_smooth}\NormalTok{(}\AttributeTok{method=}\StringTok{"lm"}\NormalTok{) }\SpecialCharTok{+}
        \FunctionTok{geom\_point}\NormalTok{() }\SpecialCharTok{+}
        \FunctionTok{stat\_regline\_equation}\NormalTok{(}\AttributeTok{label.x=}\DecValTok{5}\NormalTok{, }\AttributeTok{label.y=}\DecValTok{50}\NormalTok{) }\SpecialCharTok{+}
        \FunctionTok{stat\_cor}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{label=}\NormalTok{..rr.label..), }\AttributeTok{label.x=}\DecValTok{5}\NormalTok{, }\AttributeTok{label.y=}\DecValTok{45}\NormalTok{) }\SpecialCharTok{+} \FunctionTok{labs}\NormalTok{( }\AttributeTok{x=}\StringTok{"Petrol Pressure"}\NormalTok{, }\AttributeTok{y=}\StringTok{"Hydrocarbon escaping"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## `geom_smooth()` using formula 'y ~ x'
\end{verbatim}

\includegraphics{midterm_pt2_mir_files/figure-latex/unnamed-chunk-8-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cor}\NormalTok{(}\AttributeTok{x=}\NormalTok{ df}\SpecialCharTok{$}\NormalTok{X4, }\AttributeTok{y=}\NormalTok{ df}\SpecialCharTok{$}\NormalTok{Y)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.9213333
\end{verbatim}

\emph{So based on the graph and the correlation value we can say that
the relation is linear, pretty strong and positive. There seems to be
one outlier for X4 = 5.8}

\hypertarget{q-3}{%
\section{Q-3}\label{q-3}}

\#\#Least Square Regression Line

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#create plot with regression line, regression equation, and R{-}squared}
\FunctionTok{ggplot}\NormalTok{(}\AttributeTok{data=}\NormalTok{df, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x=}\NormalTok{X4, }\AttributeTok{y=}\NormalTok{Y)) }\SpecialCharTok{+}
        \FunctionTok{geom\_smooth}\NormalTok{(}\AttributeTok{method=}\StringTok{"lm"}\NormalTok{) }\SpecialCharTok{+}
        \FunctionTok{geom\_point}\NormalTok{() }\SpecialCharTok{+}
        \FunctionTok{stat\_regline\_equation}\NormalTok{(}\AttributeTok{label.x=}\DecValTok{5}\NormalTok{, }\AttributeTok{label.y=}\DecValTok{50}\NormalTok{) }\SpecialCharTok{+}
        \FunctionTok{stat\_cor}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{label=}\NormalTok{..rr.label..), }\AttributeTok{label.x=}\DecValTok{5}\NormalTok{, }\AttributeTok{label.y=}\DecValTok{45}\NormalTok{) }\SpecialCharTok{+} \FunctionTok{labs}\NormalTok{( }\AttributeTok{x=}\StringTok{"Petrol Pressure"}\NormalTok{, }\AttributeTok{y=}\StringTok{"Hydrocarbon escaping"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## `geom_smooth()` using formula 'y ~ x'
\end{verbatim}

\includegraphics{midterm_pt2_mir_files/figure-latex/unnamed-chunk-10-1.pdf}
\#\# testing df

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{t\_df }\OtherTok{=} \FunctionTok{data.frame}\NormalTok{(}\AttributeTok{X4 =} \FunctionTok{c}\NormalTok{(}\FloatTok{3.4}\NormalTok{,}\DecValTok{4}\NormalTok{,}\FloatTok{4.5}\NormalTok{))}
\NormalTok{t\_df}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    X4
## 1 3.4
## 2 4.0
## 3 4.5
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{intercept }\OtherTok{\textless{}{-}}\NormalTok{ fit}\SpecialCharTok{$}\NormalTok{coefficients[}\DecValTok{1}\NormalTok{]}
\NormalTok{slope }\OtherTok{\textless{}{-}}\NormalTok{ fit}\SpecialCharTok{$}\NormalTok{coefficients[}\DecValTok{2}\NormalTok{]}
\NormalTok{intercept}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## (Intercept) 
##    4.305422
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{slope}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    df$X4 
## 6.202851
\end{verbatim}

\hypertarget{predict_sales---intercept-slopex}{%
\subsubsection{predict\_sales \textless- intercept +
slope*(x)}\label{predict_sales---intercept-slopex}}

\hypertarget{y-4.305422-6.202851x}{%
\subsubsection{Y = 4.305422 + 6.202851(X)}\label{y-4.305422-6.202851x}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{t\_df}\SpecialCharTok{$}\NormalTok{pred\_Y }\OtherTok{=}\NormalTok{ intercept }\SpecialCharTok{+}\NormalTok{ slope}\SpecialCharTok{*}\NormalTok{(t\_df}\SpecialCharTok{$}\NormalTok{X4)}
\NormalTok{t\_df}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    X4   pred_Y
## 1 3.4 25.39512
## 2 4.0 29.11683
## 3 4.5 32.21825
\end{verbatim}

\hypertarget{q-4}{%
\section{Q-4}\label{q-4}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{df.lm }\OtherTok{=} \FunctionTok{lm}\NormalTok{(Y }\SpecialCharTok{\textasciitilde{}}\NormalTok{ X4, }\AttributeTok{data=}\NormalTok{df) }
\NormalTok{df.res }\OtherTok{=} \FunctionTok{resid}\NormalTok{(df.lm)}
\NormalTok{df}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 32 x 6
##    Index    X1    X2    X3    X4     Y
##    <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>
##  1     1    33    53  3.32  3.42    29
##  2     2    31    36  3.1   3.26    24
##  3     3    33    51  3.18  3.18    26
##  4     4    37    51  3.39  3.08    22
##  5     5    36    54  3.2   3.41    27
##  6     6    35    35  3.03  3.03    21
##  7     7    59    56  4.78  4.57    33
##  8     8    60    60  4.72  4.72    34
##  9     9    59    60  4.6   4.41    32
## 10    10    60    60  4.53  4.53    34
## # ... with 22 more rows
\end{verbatim}

\hypertarget{residual-values}{%
\subsection{Residual values}\label{residual-values}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{df.res}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##          1          2          3          4          5          6          7 
##  3.4808267 -0.5267171  1.9695110 -1.4102039  1.5428552 -2.1000613  0.3475479 
##          8          9         10         11         12         13         14 
##  0.4171202  0.3400041  1.5956620 -2.6038332  4.6501466  2.2779756 -5.7446559 
##         15         16         17         18         19         20         21 
## -1.9533729  0.4640611 -5.8645250 -2.9659506  4.4833366  2.6618783 -0.6130550 
##         22         23         24         25         26         27         28 
## -3.7052588 -9.2819590 -0.2442399  6.0223177  7.2628879  4.5654867 -2.2408840 
##         29         30         31         32 
##  1.5956620 -1.6809494 -4.3708068  1.6291932
\end{verbatim}

\hypertarget{residual-plot}{%
\subsection{Residual plot}\label{residual-plot}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot}\NormalTok{(df}\SpecialCharTok{$}\NormalTok{Y, df.res, }\AttributeTok{ylab=}\StringTok{"Residuals"}\NormalTok{, }\AttributeTok{xlab=}\StringTok{"Y"}\NormalTok{, }\AttributeTok{main=}\StringTok{"Residual plot"}\NormalTok{, }\AttributeTok{pch=}\DecValTok{19}\NormalTok{) }
\FunctionTok{abline}\NormalTok{(}\DecValTok{0}\NormalTok{, }\DecValTok{0}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{midterm_pt2_mir_files/figure-latex/unnamed-chunk-16-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{mean}\NormalTok{(df.res)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] -9.714451e-17
\end{verbatim}

\emph{So the mean is pretty close to zero. The data seems a little over
fitted though.}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{t\_df }\OtherTok{=} \FunctionTok{filter}\NormalTok{(df[,}\DecValTok{5}\SpecialCharTok{:}\DecValTok{6}\NormalTok{], X4 }\SpecialCharTok{\%in\%} \FunctionTok{c}\NormalTok{(}\FloatTok{3.45}\NormalTok{,}\FloatTok{4.02}\NormalTok{,}\FloatTok{5.8}\NormalTok{))}
\NormalTok{t\_df}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 3 x 2
##      X4     Y
##   <dbl> <dbl>
## 1  3.45    22
## 2  5.8     31
## 3  4.02    27
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{t\_df}\SpecialCharTok{$}\NormalTok{pred\_Y }\OtherTok{=}\NormalTok{ intercept }\SpecialCharTok{+}\NormalTok{ slope}\SpecialCharTok{*}\NormalTok{(t\_df}\SpecialCharTok{$}\NormalTok{X4)}
\NormalTok{t\_df}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 3 x 3
##      X4     Y pred_Y
##   <dbl> <dbl>  <dbl>
## 1  3.45    22   25.7
## 2  5.8     31   40.3
## 3  4.02    27   29.2
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{t\_df}\SpecialCharTok{$}\NormalTok{res }\OtherTok{=}\NormalTok{ t\_df}\SpecialCharTok{$}\NormalTok{Y}\SpecialCharTok{{-}}\NormalTok{t\_df}\SpecialCharTok{$}\NormalTok{pred\_Y}
\NormalTok{t\_df}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 3 x 4
##      X4     Y pred_Y   res
##   <dbl> <dbl>  <dbl> <dbl>
## 1  3.45    22   25.7 -3.71
## 2  5.8     31   40.3 -9.28
## 3  4.02    27   29.2 -2.24
\end{verbatim}

\hypertarget{q-5}{%
\section{Q-5}\label{q-5}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{qqnorm}\NormalTok{(df}\SpecialCharTok{$}\NormalTok{Y, }\AttributeTok{pch =} \DecValTok{1}\NormalTok{, }\AttributeTok{frame =} \ConstantTok{FALSE}\NormalTok{)}
\FunctionTok{qqline}\NormalTok{(df}\SpecialCharTok{$}\NormalTok{Y, }\AttributeTok{col =} \StringTok{"steelblue"}\NormalTok{, }\AttributeTok{lwd =} \DecValTok{2}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{midterm_pt2_mir_files/figure-latex/unnamed-chunk-21-1.pdf}

\emph{It seems like a good fit to as it is close to a straight line. The
distribution of Hydrocarbon escaping values is close to Normal}

\end{document}
